version: "3"

services:
  dhcpd:
    build: ./dhcpd
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dhcpd/dhcp:/etc/dhcp/
      # Optional: define listening interface
      # - ./dhcpd/etc/default:/etc/default/isc-dhcp-server
      - isc-dhcp-leases:/var/lib/dhcp/
    network_mode: "host"
    restart: always
volumes:
  isc-dhcp-leases:
